### ISSUE TITLE
expand available payloads for more control

### ISSUE THREAD

**Issue by ryanramage** [stoner221/hisense-remote#1]
Hi there, I am curious where you found the POWER_PAYLOAD? I would like to expand the control over the tv are there other payloads or ways to discover what other payloads might be? 

Thanks!

**Comment by stoner221** [comment]
Hey ryanramage so i decompiled the hisense remote app they have also sniffed out the traffic but after heavy looking i found that there needs to be a app connection made then payload sent after connection has been stablished. also they use an encryption key and some other stuff to get its off message sent or other messages. i actually switched to inferred modules to control everything from my xbox to my tv through the home app.

**Comment by ryanramage** [comment]
OK thanks for the info. 

I did try that hisense app last night, and while it recognized the tv, it was not able to control it. So I assume things have changed anyway in different models.   

I can see how switching to infrared would be easier. Too bad vendors dont publish info on this stuff. So I think I will give up.

Thanks
